// Curated built-in service registry. A service is config: URLs, icon color, policy.
// multiAccountPolicy: 'ok' | 'warn' | 'one-per-person' (drives warning banners)
// extraHosts: additional hosts the service's own login flow lands on (e.g. a separate auth domain),
//             so saved-login capture/fill is allowed there too. Keep this list tight — every host here
//             is trusted with that account's password.
// tokenHint: shown in the token field so the user knows which kind of credential the status card wants.
module.exports = [
  // ---- hosting / deploy ----
  { key: 'vercel',       name: 'Vercel',       dashboardUrl: 'https://vercel.com/dashboard',            loginUrl: 'https://vercel.com/login',                       signupUrl: 'https://vercel.com/signup',                        color: '#000000', multiAccountPolicy: 'warn', tokenHint: 'Vercel access token (Settings → Tokens)' },
  { key: 'netlify',      name: 'Netlify',      dashboardUrl: 'https://app.netlify.com',                 loginUrl: 'https://app.netlify.com/login',                  signupUrl: 'https://app.netlify.com/signup',                   color: '#00c7b7', multiAccountPolicy: 'warn', tokenHint: 'Netlify personal access token' },
  { key: 'cloudflare',   name: 'Cloudflare',   dashboardUrl: 'https://dash.cloudflare.com',             loginUrl: 'https://dash.cloudflare.com/login',              signupUrl: 'https://dash.cloudflare.com/sign-up',              color: '#f6821f', multiAccountPolicy: 'warn', tokenHint: 'API token with Zone:Read' },
  { key: 'railway',      name: 'Railway',      dashboardUrl: 'https://railway.com/dashboard',           loginUrl: 'https://railway.com/login',                      signupUrl: 'https://railway.com/signup',                       color: '#a77dfb', multiAccountPolicy: 'one-per-person', tokenHint: 'Railway account token' },
  { key: 'render',       name: 'Render',       dashboardUrl: 'https://dashboard.render.com',            loginUrl: 'https://dashboard.render.com/login',             signupUrl: 'https://dashboard.render.com/register',            color: '#46e3b7', multiAccountPolicy: 'ok', tokenHint: 'Render API key (rnd_…)' },
  { key: 'fly',          name: 'Fly.io',       dashboardUrl: 'https://fly.io/dashboard',                loginUrl: 'https://fly.io/app/sign-in',                     signupUrl: 'https://fly.io/app/sign-up',                       color: '#7b3fe4', multiAccountPolicy: 'ok', tokenHint: 'Fly.io access token (fo1_… / FlyV1 …)' },
  { key: 'heroku',       name: 'Heroku',       dashboardUrl: 'https://dashboard.heroku.com/apps',       loginUrl: 'https://id.heroku.com/login',                    signupUrl: 'https://signup.heroku.com/',                       color: '#430098', multiAccountPolicy: 'warn', tokenHint: 'Heroku API key (Account settings)' },
  { key: 'digitalocean', name: 'DigitalOcean', dashboardUrl: 'https://cloud.digitalocean.com/',         loginUrl: 'https://cloud.digitalocean.com/login',           signupUrl: 'https://cloud.digitalocean.com/registrations/new', color: '#0080ff', multiAccountPolicy: 'warn', tokenHint: 'Personal access token with read scope (dop_v1_…)' },
  // ---- data ----
  { key: 'supabase',     name: 'Supabase',     dashboardUrl: 'https://supabase.com/dashboard',          loginUrl: 'https://supabase.com/dashboard/sign-in',         signupUrl: 'https://supabase.com/dashboard/sign-up',           color: '#3ecf8e', multiAccountPolicy: 'warn', tokenHint: 'Supabase access token (sbp_…)' },
  { key: 'neon',         name: 'Neon',         dashboardUrl: 'https://console.neon.tech/app/projects',  loginUrl: 'https://console.neon.tech/login',                signupUrl: 'https://console.neon.tech/signup',                 color: '#00e599', multiAccountPolicy: 'ok', tokenHint: 'Neon API key (Account settings → API keys)' },
  // ---- code and packages ----
  { key: 'github',       name: 'GitHub',       dashboardUrl: 'https://github.com',                      loginUrl: 'https://github.com/login',                       signupUrl: 'https://github.com/signup',                        color: '#238636', multiAccountPolicy: 'one-per-person', tokenHint: 'Fine-grained PAT (github_pat_…) or classic (ghp_…)' },
  { key: 'gitlab',       name: 'GitLab',       dashboardUrl: 'https://gitlab.com/dashboard/projects',   loginUrl: 'https://gitlab.com/users/sign_in',               signupUrl: 'https://gitlab.com/users/sign_up',                 color: '#fc6d26', multiAccountPolicy: 'ok', tokenHint: 'Personal access token with read_api (glpat-…)' },
  { key: 'npm',          name: 'npm',          dashboardUrl: 'https://www.npmjs.com/',                  loginUrl: 'https://www.npmjs.com/login',                    signupUrl: 'https://www.npmjs.com/signup',                     color: '#cb3837', multiAccountPolicy: 'ok', tokenHint: 'Read-only access token (npm_…)' },
  { key: 'pypi',         name: 'PyPI',         dashboardUrl: 'https://pypi.org/manage/projects/',       loginUrl: 'https://pypi.org/account/login/',                signupUrl: 'https://pypi.org/account/register/',               color: '#3775a9', multiAccountPolicy: 'ok' },
  { key: 'dockerhub',    name: 'Docker Hub',   dashboardUrl: 'https://hub.docker.com/repositories',     loginUrl: 'https://hub.docker.com/login',                   signupUrl: 'https://hub.docker.com/signup',                    color: '#2496ed', multiAccountPolicy: 'ok', extraHosts: ['login.docker.com'], tokenHint: 'username:personal-access-token (read-only PAT)' },
  { key: 'huggingface',  name: 'Hugging Face', dashboardUrl: 'https://huggingface.co/',                 loginUrl: 'https://huggingface.co/login',                   signupUrl: 'https://huggingface.co/join',                      color: '#ffd21e', multiAccountPolicy: 'ok', tokenHint: 'User access token with read role (hf_…)' },
  // ---- payments ----
  { key: 'stripe',       name: 'Stripe',       dashboardUrl: 'https://dashboard.stripe.com/',           loginUrl: 'https://dashboard.stripe.com/login',             signupUrl: 'https://dashboard.stripe.com/register',            color: '#635bff', multiAccountPolicy: 'ok', tokenHint: 'Restricted key with read access (rk_live_… / rk_test_…)' },
];
