// Curated built-in service registry. A service is config: URLs, icon color, policy.
// multiAccountPolicy: 'ok' | 'warn' | 'one-per-person' (drives warning banners)
// extraHosts: additional hosts the service's own login flow lands on (e.g. a separate auth domain),
//             so saved-login capture/fill is allowed there too. Keep this list tight — every host here
//             is trusted with that account's password.
// tokenHint: shown in the token field so the user knows which kind of credential the status card wants.
// category: rail/Home grouping — see CATEGORIES in ui.js.
// Google: sign-in WORKS with Electron's default user agent (Google serves its lite flow and looks the
// account up); stripping the Electron UA token makes Google serve the full flow and then reject the
// browser (verified 2026-09-07, see WORKING-NOTES). Do not change the user agent.
module.exports = [
  // ---- hosting / deploy ----
  { key: 'vercel',       name: 'Vercel', category: 'hosting',       dashboardUrl: 'https://vercel.com/dashboard',            loginUrl: 'https://vercel.com/login',                       signupUrl: 'https://vercel.com/signup',                        color: '#000000', multiAccountPolicy: 'warn', tokenHint: 'Vercel access token (Settings → Tokens)' },
  { key: 'netlify',      name: 'Netlify', category: 'hosting',      dashboardUrl: 'https://app.netlify.com',                 loginUrl: 'https://app.netlify.com/login',                  signupUrl: 'https://app.netlify.com/signup',                   color: '#00c7b7', multiAccountPolicy: 'warn', tokenHint: 'Netlify personal access token' },
  { key: 'cloudflare',   name: 'Cloudflare', category: 'hosting',   dashboardUrl: 'https://dash.cloudflare.com',             loginUrl: 'https://dash.cloudflare.com/login',              signupUrl: 'https://dash.cloudflare.com/sign-up',              color: '#f6821f', multiAccountPolicy: 'warn', tokenHint: 'API token with Zone:Read' },
  { key: 'railway',      name: 'Railway', category: 'hosting',      dashboardUrl: 'https://railway.com/dashboard',           loginUrl: 'https://railway.com/login',                      signupUrl: 'https://railway.com/signup',                       color: '#a77dfb', multiAccountPolicy: 'one-per-person', tokenHint: 'Railway account token' },
  { key: 'render',       name: 'Render', category: 'hosting',       dashboardUrl: 'https://dashboard.render.com',            loginUrl: 'https://dashboard.render.com/login',             signupUrl: 'https://dashboard.render.com/register',            color: '#46e3b7', multiAccountPolicy: 'ok', tokenHint: 'Render API key (rnd_…)' },
  { key: 'fly',          name: 'Fly.io', category: 'hosting',       dashboardUrl: 'https://fly.io/dashboard',                loginUrl: 'https://fly.io/app/sign-in',                     signupUrl: 'https://fly.io/app/sign-up',                       color: '#7b3fe4', multiAccountPolicy: 'ok', tokenHint: 'Fly.io access token (fo1_… / FlyV1 …)' },
  { key: 'heroku',       name: 'Heroku', category: 'hosting',       dashboardUrl: 'https://dashboard.heroku.com/apps',       loginUrl: 'https://id.heroku.com/login',                    signupUrl: 'https://signup.heroku.com/',                       color: '#430098', multiAccountPolicy: 'warn', tokenHint: 'Heroku API key (Account settings)' },
  { key: 'digitalocean', name: 'DigitalOcean', category: 'hosting', dashboardUrl: 'https://cloud.digitalocean.com/',         loginUrl: 'https://cloud.digitalocean.com/login',           signupUrl: 'https://cloud.digitalocean.com/registrations/new', color: '#0080ff', multiAccountPolicy: 'warn', tokenHint: 'Personal access token with read scope (dop_v1_…)' },
  // ---- data ----
  { key: 'supabase',     name: 'Supabase', category: 'data',     dashboardUrl: 'https://supabase.com/dashboard',          loginUrl: 'https://supabase.com/dashboard/sign-in',         signupUrl: 'https://supabase.com/dashboard/sign-up',           color: '#3ecf8e', multiAccountPolicy: 'warn', tokenHint: 'Supabase access token (sbp_…)' },
  { key: 'neon',         name: 'Neon', category: 'data',         dashboardUrl: 'https://console.neon.tech/app/projects',  loginUrl: 'https://console.neon.tech/login',                signupUrl: 'https://console.neon.tech/signup',                 color: '#00e599', multiAccountPolicy: 'ok', tokenHint: 'Neon API key (Account settings → API keys)' },
  // ---- code and packages ----
  { key: 'github',       name: 'GitHub', category: 'code',       dashboardUrl: 'https://github.com',                      loginUrl: 'https://github.com/login',                       signupUrl: 'https://github.com/signup',                        color: '#238636', multiAccountPolicy: 'one-per-person', tokenHint: 'Fine-grained PAT (github_pat_…) or classic (ghp_…)' },
  { key: 'gitlab',       name: 'GitLab', category: 'code',       dashboardUrl: 'https://gitlab.com/dashboard/projects',   loginUrl: 'https://gitlab.com/users/sign_in',               signupUrl: 'https://gitlab.com/users/sign_up',                 color: '#fc6d26', multiAccountPolicy: 'ok', tokenHint: 'Personal access token with read_api (glpat-…)' },
  { key: 'npm',          name: 'npm', category: 'code',          dashboardUrl: 'https://www.npmjs.com/',                  loginUrl: 'https://www.npmjs.com/login',                    signupUrl: 'https://www.npmjs.com/signup',                     color: '#cb3837', multiAccountPolicy: 'ok', tokenHint: 'Read-only access token (npm_…)' },
  { key: 'pypi',         name: 'PyPI', category: 'code',         dashboardUrl: 'https://pypi.org/manage/projects/',       loginUrl: 'https://pypi.org/account/login/',                signupUrl: 'https://pypi.org/account/register/',               color: '#3775a9', multiAccountPolicy: 'ok' },
  { key: 'dockerhub',    name: 'Docker Hub', category: 'code',   dashboardUrl: 'https://hub.docker.com/repositories',     loginUrl: 'https://hub.docker.com/login',                   signupUrl: 'https://hub.docker.com/signup',                    color: '#2496ed', multiAccountPolicy: 'ok', extraHosts: ['login.docker.com'], tokenHint: 'username:personal-access-token (read-only PAT)' },
  { key: 'huggingface',  name: 'Hugging Face', category: 'code', dashboardUrl: 'https://huggingface.co/',                 loginUrl: 'https://huggingface.co/login',                   signupUrl: 'https://huggingface.co/join',                      color: '#ffd21e', multiAccountPolicy: 'ok', tokenHint: 'User access token with read role (hf_…)' },
  // ---- payments ----
  { key: 'stripe',       name: 'Stripe', category: 'payments',       dashboardUrl: 'https://dashboard.stripe.com/',           loginUrl: 'https://dashboard.stripe.com/login',             signupUrl: 'https://dashboard.stripe.com/register',            color: '#635bff', multiAccountPolicy: 'ok', tokenHint: 'Restricted key with read access (rk_live_… / rk_test_…)' },
  // ---- google ----
  { key: 'google',       name: 'Google Account',   category: 'google', dashboardUrl: 'https://myaccount.google.com/',          loginUrl: 'https://accounts.google.com/ServiceLogin?continue=https%3A%2F%2Fmyaccount.google.com%2F',          signupUrl: 'https://accounts.google.com/signup', color: '#4285f4', multiAccountPolicy: 'ok' },
  { key: 'gmail',        name: 'Gmail',            category: 'google', dashboardUrl: 'https://mail.google.com/mail/',        loginUrl: 'https://accounts.google.com/ServiceLogin?continue=https%3A%2F%2Fmail.google.com%2Fmail%2F',        signupUrl: 'https://accounts.google.com/signup', color: '#ea4335', multiAccountPolicy: 'ok' },
  { key: 'gcloud',       name: 'Google Cloud',     category: 'google', dashboardUrl: 'https://console.cloud.google.com/',    loginUrl: 'https://accounts.google.com/ServiceLogin?continue=https%3A%2F%2Fconsole.cloud.google.com%2F',    signupUrl: 'https://accounts.google.com/signup', color: '#34a853', multiAccountPolicy: 'ok' },
  { key: 'firebase',     name: 'Firebase',         category: 'google', dashboardUrl: 'https://console.firebase.google.com/', loginUrl: 'https://accounts.google.com/ServiceLogin?continue=https%3A%2F%2Fconsole.firebase.google.com%2F', signupUrl: 'https://accounts.google.com/signup', color: '#ffca28', multiAccountPolicy: 'ok' },
  { key: 'gworkspace',   name: 'Google Workspace Admin', category: 'google', dashboardUrl: 'https://admin.google.com/',      loginUrl: 'https://accounts.google.com/ServiceLogin?continue=https%3A%2F%2Fadmin.google.com%2F',              signupUrl: 'https://workspace.google.com/business/signup/welcome', color: '#fbbc04', multiAccountPolicy: 'ok' },
  { key: 'gplay',        name: 'Google Play Console', category: 'google', dashboardUrl: 'https://play.google.com/console/',  loginUrl: 'https://accounts.google.com/ServiceLogin?continue=https%3A%2F%2Fplay.google.com%2Fconsole%2F',     signupUrl: 'https://accounts.google.com/signup', color: '#01875f', multiAccountPolicy: 'ok' },
  { key: 'aistudio',     name: 'Google AI Studio', category: 'google', dashboardUrl: 'https://aistudio.google.com/',         loginUrl: 'https://accounts.google.com/ServiceLogin?continue=https%3A%2F%2Faistudio.google.com%2F',           signupUrl: 'https://accounts.google.com/signup', color: '#8e44ad', multiAccountPolicy: 'ok' },
  // ---- microsoft ----
  { key: 'microsoft',    name: 'Microsoft Account', category: 'microsoft', dashboardUrl: 'https://account.microsoft.com/',  loginUrl: 'https://login.live.com/',            signupUrl: 'https://signup.live.com/',                         color: '#0078d4', multiAccountPolicy: 'ok', extraHosts: ['login.microsoft.com', 'login.microsoftonline.com'] },
  { key: 'outlook',      name: 'Outlook',          category: 'microsoft', dashboardUrl: 'https://outlook.live.com/mail/',  loginUrl: 'https://login.live.com/',            signupUrl: 'https://signup.live.com/',                         color: '#0f6cbd', multiAccountPolicy: 'ok', extraHosts: ['login.microsoft.com', 'login.microsoftonline.com', 'outlook.office.com'] },
  { key: 'azure',        name: 'Azure',            category: 'microsoft', dashboardUrl: 'https://portal.azure.com/',       loginUrl: 'https://login.microsoftonline.com/', signupUrl: 'https://azure.microsoft.com/free/',                color: '#0089d6', multiAccountPolicy: 'ok', extraHosts: ['login.live.com', 'login.microsoft.com'] },
  { key: 'm365admin',    name: 'Microsoft 365 Admin', category: 'microsoft', dashboardUrl: 'https://admin.microsoft.com/', loginUrl: 'https://login.microsoftonline.com/', signupUrl: 'https://www.microsoft.com/microsoft-365/business', color: '#d83b01', multiAccountPolicy: 'ok', extraHosts: ['login.live.com', 'login.microsoft.com'] },
  // ---- mail ----
  { key: 'proton',       name: 'Proton Mail',      category: 'mail', dashboardUrl: 'https://mail.proton.me/',              loginUrl: 'https://account.proton.me/login',    signupUrl: 'https://account.proton.me/signup',                 color: '#6d4aff', multiAccountPolicy: 'ok' },
  { key: 'zoho',         name: 'Zoho Mail',        category: 'mail', dashboardUrl: 'https://mail.zoho.com/',               loginUrl: 'https://accounts.zoho.com/signin',   signupUrl: 'https://www.zoho.com/mail/signup.html',            color: '#e42527', multiAccountPolicy: 'ok', extraHosts: ['accounts.zoho.eu'] },
  { key: 'fastmail',     name: 'Fastmail',         category: 'mail', dashboardUrl: 'https://app.fastmail.com/',            loginUrl: 'https://app.fastmail.com/login',     signupUrl: 'https://app.fastmail.com/signup',                  color: '#0067b9', multiAccountPolicy: 'ok' },
  { key: 'yahoo',        name: 'Yahoo Mail',       category: 'mail', dashboardUrl: 'https://mail.yahoo.com/',              loginUrl: 'https://login.yahoo.com/',           signupUrl: 'https://login.yahoo.com/account/create',           color: '#6001d2', multiAccountPolicy: 'ok' },
  { key: 'tuta',         name: 'Tuta Mail',        category: 'mail', dashboardUrl: 'https://app.tuta.com/',                loginUrl: 'https://app.tuta.com/login',         signupUrl: 'https://app.tuta.com/signup',                      color: '#a01e20', multiAccountPolicy: 'ok' },
  { key: 'icloud',       name: 'iCloud Mail',      category: 'mail', dashboardUrl: 'https://www.icloud.com/mail/',         loginUrl: 'https://www.icloud.com/',            signupUrl: 'https://account.apple.com/account',                color: '#3693f3', multiAccountPolicy: 'ok', extraHosts: ['idmsa.apple.com', 'appleid.apple.com', 'account.apple.com'] },
  // ---- cloud ----
  { key: 'aws',          name: 'AWS',              category: 'cloud', dashboardUrl: 'https://console.aws.amazon.com/',     loginUrl: 'https://signin.aws.amazon.com/',     signupUrl: 'https://portal.aws.amazon.com/billing/signup',     color: '#ff9900', multiAccountPolicy: 'ok', extraHosts: ['us-east-1.signin.aws.amazon.com'] },
  // ---- ai ----
  { key: 'openai',       name: 'OpenAI Platform',  category: 'ai', dashboardUrl: 'https://platform.openai.com/',           loginUrl: 'https://platform.openai.com/login',  signupUrl: 'https://platform.openai.com/signup',               color: '#10a37f', multiAccountPolicy: 'warn', extraHosts: ['auth.openai.com'] },
  { key: 'anthropic',    name: 'Claude Platform (Anthropic)', category: 'ai', dashboardUrl: 'https://platform.claude.com/', loginUrl: 'https://platform.claude.com/login', signupUrl: 'https://platform.claude.com/login', color: '#d97757', multiAccountPolicy: 'warn', extraHosts: ['console.anthropic.com'] },
];
